Adding support for tape jobs
tigattack/VeeamNotify pull request #81
Opened 2024-09-18 07:14 UTC by GoryMadLogger

Add logic to grab a tape job vs normal job, the logic for Agent Backup and Tape Jobs are the same so has been reused.

![image](https://github.com/user-attachments/assets/5dbf4069-c310-4050-85f0-153aaf2e54ec)
![image](https://github.com/user-attachments/assets/60bddf97-ffb0-49ca-acb6-eb3ad74c44c6)
![image](https://github.com/user-attachments/assets/b83b335d-8d74-461b-8c83-337d7a1ba46d)

2024-09-18 21:12 UTC, tigattack commented
Thanks for the PR, this is great! I'll review ASAP 🙏

2025-04-22 12:08 UTC, tigattack requested changes
Hey, really sorry for the delay, been super busy for a while and this project has taken a bit of a back seat...

I have a couple of comments, but otherwise this all looks good to me. I'm unable to test it myself as I don't have any tape infrastructure, but I trust it's well tested (you've included some screenshots so clearly it's working to some level! 😄) and am happy to merge once my comments are resolved.

Thanks again for the PR!

2025-04-22 12:08 UTC, tigattack commented on Bootstrap.ps1
>  	Write-LogMessage -Tag 'ERROR' -Message "Job type '$($job.JobType)' is not supported."
```suggestion
	Write-LogMessage -Tag 'ERROR' -Message "Job type '$($JobType)' is not supported."
```

Can use the new `$JobType` var here for consistency.

2025-04-22 12:08 UTC, tigattack commented on resources/NotificationHandler.psm1
Please also add support for tape jobs in Slack & MS Teams reports.

2025-04-22 18:21 UTC, GoryMadLogger commented on resources/NotificationHandler.psm1
Realised that the params are actually the same (for now anyways so was easy to add in support), Unfortunately I don't use any of the other 3 but don't see why they would have any issues since discord works ok

2025-04-22 20:39 UTC, tigattack commented on resources/version.txt
> +v1.0.2
```suggestion
v1.1.0
```

Sorry, this slipped past me before... This project adheres to [semver](https://semver.org/) versioning, meaning this change constitutes a bump to the minor version.

2025-04-22 21:03 UTC, merged